services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: semil
      POSTGRES_PASSWORD: semil
      POSTGRES_DB: task_manager_api
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5433:5432'
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER:-semil}"]
      interval: 10s
      retries: 5
      start_period: 5s
volumes:
  postgres: